### ISSUE TITLE
ERROR: cannot list input file 

### ISSUE THREAD

**Issue by JuanMartinezV** [valdeanda/mebs#3]
Hi, I am working with a RAST-MG dataset of proteins obtained from WGS, I am trying to use mebs with the following command 
`perl mebs.pl -input /home/juanmartinez/Descargas/mebs-master/4898953.3.faa -type genomic -fdr 0.01`
but it is printing the following error: `RROR: cannot list 4898953.3.faa`

I would like to know if maybe the dataset might be the problem itself or if I skipped any important step in the process

Thanks!

**Comment by valdeanda** [comment]
Hi Juan
You should just specify the directory, just change your command to :

```
perl mebs.pl -input /home/juanmartinez/Descargas/mebs-master/ -type genomic -fdr 0.01
```
Let me know if that works 

Best

**Comment by JuanMartinezV** [comment]
Hi Valdeanda, 

It worked, thank you so much!
